apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkyRnpkR0oxYVd4a09qMXFaM2xvU0RSQVJ5az0iCgkJfQoJfQp9
kind: Secret
metadata:
  name: castbuild-sec
  namespace: castimaging-v3
type: kubernetes.io/dockerconfigjson