apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jar-rd-castimaging-v3
  region: us-east-2

vpc:
  id: "vpc-a0a0a0a0a0aa11aaa" 
  cidr: "172.31.0.0/16"       

  subnets:
    public:
      us-east-2a:
        id: "subnet-abcdabcd123412341"  
        cidr: "172.31.0.0/20"
      us-east-2b:
        id: "subnet-abcdabcd456456456"  
        cidr: "172.31.16.0/20"
      us-east-2c:
        id: "subnet-abcdabcd789789789"  
        cidr: "172.31.32.0/20"        
    
nodeGroups:
  - name: ng-1
    instanceType: t2.2xlarge
    desiredCapacity: 2
    privateNetworking: false
    iam:
      withAddonPolicies:
        ebs: true         # Enable IAM permissions for the EBS CSI driver
        efs: true         # Enable IAM permissions for the EFS CSI driver
    ssh:
      publicKeyName: eks-mykeypair   # use existing EC2 key
