apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-extendproxy-data
  namespace: castimaging-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: castimaging-storage
