kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: castimaging-ebs
  annotations:
    helm.sh/resource-policy: keep  
provisioner: ebs.csi.aws.com # Amazon EBS CSI driver
parameters:
  type: gp2
  encrypted: 'true'
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
