apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-extendproxy-v3
  namespace: castimaging-v3
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: castimaging-v3-local-storage
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/d4a45be0-a00d-498a-979f-ef768fa2956b/resourceGroups/aks-cluster-us-army_group/providers/Microsoft.Compute/disks/pv-extendproxy-v3
    fsType: ext4
  claimRef:
    namespace: castimaging-v3
    name: pvc-extendproxy-v3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-extendproxy-v3
  namespace: castimaging-v3
  labels:
    console.service: extendproxy
spec:
  volumeName: pv-extendproxy-v3
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-v3-local-storage
  resources:
    requests:
      storage: 5Gi