apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-extendproxy-v3
  namespace: castimaging-v3
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: castimaging-storage
  csi:
    driver: disk.csi.azure.com
    #volumeHandle: /subscriptions/<your-subscription-id>/resourceGroups/<your-resource-group>/providers/Microsoft.Compute/disks/pv-extendproxy-v3-disk
    fsType: ext4
  claimRef:
    namespace: castimaging-v3
    name: pvc-extendproxy-v3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-extendproxy-v3
  namespace: castimaging-v3
  labels:
    console.service: extendproxy
spec:
  volumeName: pv-extendproxy-v3
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 5Gi