apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-server-config
  namespace: castimaging-v3

  labels:
    console.service: viewer-server
spec:
   accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-server-log
  namespace: castimaging-v3

  labels:
    console.service: viewer-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-server-csv
  namespace: castimaging-v3

  labels:
    console.service: viewer-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-etl-config
  namespace: castimaging-v3

  labels:
    console.service: viewer-etl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-etl-logs
  namespace: castimaging-v3

  labels:
    console.service: viewer-etl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-etl-upload
  namespace: castimaging-v3

  labels:
    console.service: viewer-etl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-aimanager-config
  namespace: castimaging-v3

  labels:
    console.service: viewer-aimanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-aimanager-logs
  namespace: castimaging-v3

  labels:
    console.service: viewer-aimanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-aimanager-csv
  namespace: castimaging-v3

  labels:
    console.service: viewer-aimanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-storage
  resources:
    requests:
      storage: 10Mi