# For storage postgres data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: castimaging-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi  # Default for Postgres, change according to deployment and applications in portfolio
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restapi-domains
  namespace: castimaging-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
---
# For storage of CASTMS, Extensions, Logs and this is specific to POD
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castdir-console-analysis-node-core-0
  namespace: castimaging-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
---
# For storage of shared data for deploy, delivery and common data. This is shared with other analysis nodes PODs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-console-analysis-node-core-0
  namespace: castimaging-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: gp2