apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: castimaging-storage
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
  kind: Managed
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true