apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: castimaging-storage
provisioner: ebs.csi.aws.com  # AWS EBS CSI driver provisioner
parameters:
  type: gp3  # EBS volume type. Use gp3, gp2, io1, etc.
  fsType: ext4  # Filesystem type (ext4 is default; can use xfs or others if needed)
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true  # Allow dynamic resizing
