apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: castimaging-v3-local-storage
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS
  kind: Managed
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true