# Default values for imaging-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 3.0.0

# Define the namespace here
namespace: castimaging-v3

# Storage class configuration
storage:
  className: cast-gp2
  EFSclassName: cast-efs

# Network access
CloudFrontDomain: d313reevm4vbam.cloudfront.net

#
# Console  
#
ConsolePostgresReplicaCount: 1
SSOServiceReplicaCount: 1
ConsoleServiceReplicaCount: 1
GatewayServiceReplicaCount: 1
AnalysisNodeReplicaCount: 1
ControlPaneReplicaCount: 1
AuthenticationServiceReplicaCount: 1
IntegratedDashboardsReplicaCount: 1
#
# Viewer
#
ViewerNeo4jReplicaCount: 1
ViewerServerReplicaCount: 1
ViewerEtlReplicaCount: 1
ViewerAiManagerReplicaCount: 1
#
# ExtendProxy
#
ExtendProxyReplicaCount: 1
ExtendProxy:
  exthostname: a56c82ab1898e4a239d7a557fb4231df-1101772276.us-east-2.elb.amazonaws.com
  pubextendurl: "https://extend.castsoftware.com"

#
# Console images
#
ConsolePostgresImage:
  name: quay.io/enterprisedb/postgresql
  tag: 13.3
  pullPolicy: IfNotPresent
ConsoleSSOServiceImage:
  name: jartero/sso-service
  tag: us-army-latest
  pullPolicy: IfNotPresent
ConsoleServiceImage:
  name: jartero/console
  tag: us-army-latest
  pullPolicy: IfNotPresent
ConsoleGatewayServiceImage:
  name: jartero/gateway
  tag: us-army-latest
  pullPolicy: IfNotPresent  
ConsoleAnalysisNodeImage:
  name: jartero/analysis-node
  tag: us-army-latest
  pullPolicy: IfNotPresent
ConsoleControlPaneImage:
  name: jartero/admin-center
  tag: us-army-latest
  pullPolicy: IfNotPresent
ConsoleAuthenticationServiceImage:
  name: jartero/auth-service
  tag: us-army-latest
  pullPolicy: IfNotPresent
ConsoleIntegratedDashboardsImage:
  name: jartero/dashboards
  tag: latest
  pullPolicy: IfNotPresent
  
#
# Viewer images
#
ViewerNeo4jImage:
  name: jartero/neo4j
  tag: us-army-latest
  pullPolicy: IfNotPresent
ViewerServiceImage:
  name: jartero/viewer
  tag: us-army-latest
  pullPolicy: IfNotPresent
ViewerEtlImage:
  name: jartero/etl-service
  tag: us-army-latest
  pullPolicy: IfNotPresent  
ViewerAiManagerImage:
  name: jartero/ai-service
  tag: us-army-latest
  pullPolicy: IfNotPresent
#
# ExtendProxy Image
#
ExtendProxyImage:
  name: jartero/extend-proxy
  tag: 1.0.0.1675
  pullPolicy: IfNotPresent
  
  
#
# Console resources
#
ConsolePostgresResources:
  requests:
    cpu: 2
    memory: 8G
SSOServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
ConsoleServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
GatewayServiceResources:
  requests:
    cpu: 0.1
    memory: 100M
AnalysisNodeReplicaResources:
  requests:
    cpu: 0.5
    memory: 4G
ControlPaneResources:
  requests:
    cpu: 0.1
    memory: 200M
AuthenticationServiceResources:
  requests:
    cpu: 0.1
    memory: 2G
IntegratedDashboardsResources:
  requests:
    cpu: 0.1
    memory: 100M

#
# Viewer resources
#
ViewerNeo4jResources:
  requests:
    cpu: 1
    memory: 16G
ViewerServerServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
ViewerEtlResources:
  requests:
    cpu: 0.1
    memory: 1G
ViewerAiManagerResources:
  requests:
    cpu: 0.1
    memory: 100M
    
#
# ExtendProxy resources
#
ExtendProxyResources:
  requests:
    cpu: 0.1
    memory: 100M    


