# Default values for imaging-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 3.1.1

# Define the namespace here
namespace: castimaging-v3

# Kubernetes Provider: 
# - AKS (Azure)
# - EKS (AWS)
K8SProvider: EKS

# Storage configuration
storage:
  BSdriver: ebs.csi.aws.com
  FSdriver: efs.csi.aws.com
  #BSdriver: disk.csi.azure.com
  #FSdriver: file.csi.azure.com
  BSclassName: castimaging-bs
  FSclassName: castimaging-fs
  # Below parameters are used to enable File Storage (instead of Block Storage) for the analysis-node (OPTIONAL)
  AnalysisNodeFS:
    enable: true
    # Applies to AWS EKS only:
    EFSsystemID: fs-xxx
    EFSaccessPointID: fsap-xxx

# Network access
FrontEndHost: xxx.cloudfront.net


#
# ExtendProxy
#
ExtendProxyReplicaCount: 1
ExtendProxy:
  enable: false
  exthostname: xxxxxx.yyyyy.zzzzz.com
  pubextendurl: "https://extend.castsoftware.com"
#
# Console  
#
ConsolePostgresReplicaCount: 1
SSOServiceReplicaCount: 1
ConsoleServiceReplicaCount: 1
GatewayServiceReplicaCount: 1
AnalysisNodeReplicaCount: 1
ControlPaneReplicaCount: 1
AuthenticationServiceReplicaCount: 1
IntegratedDashboardsReplicaCount: 1
#
# Viewer
#
ViewerNeo4jReplicaCount: 1
ViewerServerReplicaCount: 1
ViewerEtlReplicaCount: 1
ViewerAiManagerReplicaCount: 1

#
# Console images
#
ConsolePostgresImage:
  name: quay.io/enterprisedb/postgresql
  tag: 13.3
  pullPolicy: IfNotPresent
ConsoleSSOServiceImage:
  name: castbuild/sso-service
  tag: 3.1.1
  pullPolicy: IfNotPresent
ConsoleServiceImage:
  name: castbuild/console
  tag: 3.1.1
  pullPolicy: IfNotPresent
ConsoleGatewayServiceImage:
  name: castbuild/gateway
  tag: 3.1.1
  pullPolicy: IfNotPresent  
ConsoleAnalysisNodeImage:
  name: castbuild/analysis-node
  tag: 3.1.1.dev_core8.4.0.1497
  pullPolicy: IfNotPresent
ConsoleControlPaneImage:
  name: castbuild/admin-center
  tag: 3.1.1
  pullPolicy: IfNotPresent
ConsoleAuthenticationServiceImage:
  name: castbuild/auth-service
  tag: 3.1.1
  pullPolicy: IfNotPresent
ConsoleIntegratedDashboardsImage:
  name: castbuild/dashboards
  tag: 2.13.0-SNAPSHOT
  pullPolicy: IfNotPresent
  
#
# Viewer images
#
ViewerNeo4jImage:
  name: castbuild/neo4j
  tag: 3.1.1-84
  pullPolicy: IfNotPresent
ViewerServiceImage:
  name: castbuild/viewer
  tag: 3.1.1-84
  pullPolicy: IfNotPresent
ViewerEtlImage:
  name: castbuild/etl-service
  tag: 3.1.1-84
  pullPolicy: IfNotPresent  
ViewerAiManagerImage:
  name: castbuild/ai-service
  tag: 3.1.1-84
  pullPolicy: IfNotPresent
#
# ExtendProxy Image
#
ExtendProxyImage:
  name: castbuild/extend-proxy
  tag: 1.0.0.1468
  pullPolicy: IfNotPresent 

#
# Console resources
#
ConsolePostgresResources:
  requests:
    cpu: 1
    memory: 12G
SSOServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
ConsoleServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
GatewayServiceResources:
  requests:
    cpu: 0.1
    memory: 100M
AnalysisNodeReplicaResources:
  requests:
    cpu: 1
    memory: 4G
ControlPaneResources:
  requests:
    cpu: 0.1
    memory: 200M
AuthenticationServiceResources:
  requests:
    cpu: 0.1
    memory: 2G
IntegratedDashboardsResources:
  requests:
    cpu: 0.1
    memory: 100M

#
# Viewer resources
#
ViewerNeo4jResources:
  requests:
    cpu: 1
    memory: 16G
ViewerServerServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
ViewerEtlResources:
  requests:
    cpu: 0.1
    memory: 1G
ViewerAiManagerResources:
  requests:
    cpu: 0.1
    memory: 100M    
#
# ExtendProxy resources
#
ExtendProxyResources:
  requests:
    cpu: 0.1
    memory: 100M    

#
# Analysis folders (do not customize)
#
anadir:
  datadirmount: /shared
  deploy: /shared/deploy
  delivery: /shared/delivery
  common: /shared/common-data
  castdirmount: /usr/share/CAST
  logs: /usr/share/CAST/CAST/Logs
  lisa: /usr/share/CAST/CASTMS/LISA
  extensions: /usr/share/CAST/Extensions