# Default values for imaging-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 3.1.1

####################################################################################
#
# Define the namespace here
namespace: castimaging-v3
#
# Kubernetes Provider: 
# - For Azure, use AKS
# - For AWS, use EKS
K8SProvider: EKS
#
# External network access
FrontEndHost: xxx.cloudfront.net # EFS
#
# OPTIONAL - ExtendProxy
ExtendProxy:
  enable: true
  exthostname: xxx # Run helm-upgrade.bat after updating
  pubextendurl: "https://extend.castsoftware.com"
#
# OPTIONAL - Use custom Trust Store
UseCustomTrustStore: false  
#
# OPTIONAL - Access Private Repo with Secret
UseImagePullSecrets: true
Base64EncodedDockerconfigjson: xxx
#
# OPTIONAL - Enable shared File Storage for analysis-node
# Important note: Extra cluster configuration is required before you can enable this feature
#                 Please refer to the README files before modifying below parameters.
AnalysisNodeFS:
  enable: true  # Do not change if castimaging is already deployed
  # AWS EKS specific parameters (will be ignored if K8SProvider is set to 'AKS')
  EFSsystemID: fs-xxx
  EFSaccessPointID: fsap-xxx #fsap-0c96e8254cfd3eeb2
#
# Misc options
CreateStorageClass: true
#
Neo4jHostName: xxx.us-east-2.elb.amazonaws.com
####################################################################################

# Disk Storage (DS) and File Storage (FS) Drivers
#   EKS drivers:
EKS_DSdriver: ebs.csi.aws.com
EKS_FSdriver: efs.csi.aws.com
#   AKS drivers:
AKS_DSdriver: disk.csi.azure.com
AKS_FSdriver: file.csi.azure.com

# CAST Storage Class names
DiskClassName: castimaging-ds
FileClassName: castimaging-fs 

#
# Console  
#
ConsolePostgresReplicaCount: 1
SSOServiceReplicaCount: 1
ConsoleServiceReplicaCount: 1
GatewayServiceReplicaCount: 1
AnalysisNodeReplicaCount: 1
ControlPaneReplicaCount: 1
AuthenticationServiceReplicaCount: 1
IntegratedDashboardsReplicaCount: 1
ExtendProxyReplicaCount: 1
#
# Viewer
#
ViewerNeo4jReplicaCount: 1
ViewerServerReplicaCount: 1
ViewerEtlReplicaCount: 1
ViewerAiManagerReplicaCount: 1

#
# Console images
#
ConsolePostgresImage:
  name: postgres
  tag: 15
  pullPolicy: IfNotPresent
ConsoleSSOServiceImage:
  name: castimaging/sso-service
  tag: 3.1.1
  pullPolicy: IfNotPresent
ConsoleServiceImage:
  name: castimaging/console
  tag: 3.1.1
  pullPolicy: IfNotPresent
ConsoleGatewayServiceImage:
  name: castimaging/gateway
  tag: 3.1.1
  pullPolicy: IfNotPresent  
ConsoleAnalysisNodeImage:
  name: castimaging/analysis-node
  tag: 3.1.1_core8.4.0
  pullPolicy: IfNotPresent
ConsoleControlPaneImage:
  name: castimaging/admin-center
  tag: 3.1.1
  pullPolicy: IfNotPresent
ConsoleAuthenticationServiceImage:
  name: castimaging/auth-service
  tag: 3.1.1
  pullPolicy: IfNotPresent
ConsoleIntegratedDashboardsImage:
  name: castimaging/dashboards
  tag: 2.13.0
  pullPolicy: IfNotPresent
  
#
# Viewer images
#
ViewerNeo4jImage:
  name: castimaging/neo4j
  tag: 3.1.1
  pullPolicy: IfNotPresent
ViewerServiceImage:
  name: castbuild/viewer
  tag: 3.1.2-123
  pullPolicy: IfNotPresent
ViewerEtlImage:
  name: castbuild/etl-service
  tag: 3.1.2-123
  pullPolicy: IfNotPresent  
ViewerAiManagerImage:
  name: castimaging/ai-service
  tag: 3.1.1
  pullPolicy: IfNotPresent
#
# ExtendProxy Image
#
ExtendProxyImage:
  name: castimaging/extend-proxy
  tag: 1.0.0.5
  pullPolicy: IfNotPresent 

#
# Console resources
#
ConsolePostgresResources:
  requests:
    cpu: 1
    memory: 12G
SSOServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
ConsoleServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
GatewayServiceResources:
  requests:
    cpu: 0.1
    memory: 100M
AnalysisNodeResources:
  requests:
    cpu: 1
    memory: 4G
ControlPaneResources:
  requests:
    cpu: 0.1
    memory: 200M
AuthenticationServiceResources:
  requests:
    cpu: 0.1
    memory: 2G
IntegratedDashboardsResources:
  requests:
    cpu: 0.1
    memory: 100M

#
# Viewer resources
#
ViewerNeo4jResources:
  requests:
    cpu: 1
    memory: 12G
ViewerServerServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
ViewerEtlResources:
  requests:
    cpu: 0.1
    memory: 1G
ViewerAiManagerResources:
  requests:
    cpu: 0.1
    memory: 100M    
#
# ExtendProxy resources
#
ExtendProxyResources:
  requests:
    cpu: 0.1
    memory: 100M    

#
# Analysis folders (do not customize)
#
anadir:
  datadirmount: /shared
  deploy: /shared/deploy
  delivery: /shared/delivery
  common: /shared/common-data
  castdirmount: /usr/share/CAST
  logs: /usr/share/CAST/CAST/Logs
  lisa: /usr/share/CAST/CASTMS/LISA
  extensions: /usr/share/CAST/Extensions