# Default values for imaging-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 3.0.0

#
# Console  
#
ConsolePostgresReplicaCount: 1
SSOServiceReplicaCount: 1
ConsoleServiceReplicaCount: 1
GatewayServiceReplicaCount: 1
AnalysisNodeReplicaCount: 1
ControlPaneReplicaCount: 1
AuthenticationServiceReplicaCount: 1
IntegratedDashboardsReplicaCount: 1
#
# Viewer
#
ViewerNeo4jReplicaCount: 1
ViewerServerReplicaCount: 1
ViewerEtlReplicaCount: 1
ViewerAiManagerReplicaCount: 1
#
# ExtendProxy
#
ExtendProxyReplicaCount: 1
ExtendProxy:
  exthostname: xxx-agentpool-xxxxx-vmssxxxx
  pubextendurl: "https://extend.castsoftware.com"

#
# Console images
#
ConsolePostgresImage:
  # Azure container registry / image name
  name: registryarmy.azurecr.io/cast_imaging_services-postgres
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleSSOServiceImage:
  name: registryarmy.azurecr.io/sso-service
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleServiceImage:
  name: registryarmy.azurecr.io/console
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleGatewayServiceImage:
  name: registryarmy.azurecr.io/gateway
  tag: army-latest-aku
  pullPolicy: IfNotPresent  
ConsoleAnalysisNodeImage:
  name: registryarmy.azurecr.io/analysis-node
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleControlPaneImage:
  name: registryarmy.azurecr.io/admin-center
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleAuthenticationServiceImage:
  name: registryarmy.azurecr.io/auth-service
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleIntegratedDashboardsImage:
  name: registryarmy.azurecr.io/dashboards
  tag: army-2.12.5-SNAPSHOT-aku
  pullPolicy: IfNotPresent
  
#
# Viewer images
#
ViewerNeo4jImage:
  name: registryarmy.azurecr.io/neo4j
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ViewerServiceImage:
  name: registryarmy.azurecr.io/viewer
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ViewerEtlImage:
  name: registryarmy.azurecr.io/etl-service
  tag: army-latest-aku
  pullPolicy: IfNotPresent  
ViewerAiManagerImage:
  name: registryarmy.azurecr.io/ai-service
  tag: army-latest-aku
  pullPolicy: IfNotPresent
#
# ExtendProxy Image
#
ExtendProxyImage:
  name: registryarmy.azurecr.io/extend-proxy
  tag: army-latest-aku
  pullPolicy: IfNotPresent  
  
  
#
# Console resources
#
ConsolePostgresResources:
  requests:
    cpu: 1
    memory: 8G
SSOServiceResources:
  requests:
    cpu: 0.1
    memory: 100M
ConsoleServiceResources:
  requests:
    cpu: 0.1
    memory: 100M
GatewayServiceResources:
  requests:
    cpu: 0.1
    memory: 100M
AnalysisNodeReplicaResources:
  requests:
    cpu: 0.5
    memory: 4G
ControlPaneResources:
  requests:
    cpu: 0.1
    memory: 200M
AuthenticationServiceResources:
  requests:
    cpu: 0.1
    memory: 100M
IntegratedDashboardsResources:
  requests:
    cpu: 0.1
    memory: 100M

#
# Viewer resources
#
ViewerNeo4jResources:
  requests:
    cpu: 0.2
    memory: 16G
ViewerServerServiceResources:
  requests:
    cpu: 0.1
    memory: 1G
ViewerEtlResources:
  requests:
    cpu: 0.1
    memory: 1G
ViewerAiManagerResources:
  requests:
    cpu: 0.1
    memory: 100M
    
#
# ExtendProxy resources
#
ExtendProxyResources:
  requests:
    cpu: 0.1
    memory: 100M    
    
storageClassName:
  name: castimaging-storage
