# Default values for imaging-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 3.0.0

#
# Console  
#
ConsolePostgresReplicaCount: 1
SSOServiceReplicaCount: 1
ConsoleServiceReplicaCount: 1
GatewayServiceReplicaCount: 1
AnalysisNodeReplicaCount: 1
ControlPaneReplicaCount: 1
AuthenticationServiceReplicaCount: 1
IntegratedDashboardsReplicaCount: 1
#
# Viewer
#
ViewerNeo4jReplicaCount: 1
ViewerServerReplicaCount: 1
ViewerEtlReplicaCount: 1
ViewerAiManagerReplicaCount: 1
#
# ExtendProxy
#
ExtendProxyReplicaCount: 1
ExtendProxy:
  exthostname: aks-agentpool-13622101-vmss000000
  pubextendurl: "https://extend.castsoftware.com"

#
# Console images
#
ConsolePostgresImage:
  # Azure container registry / image name
  name: registryarmy.azurecr.io/cast_imaging_services-postgres
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleSSOServiceImage:
  name: registryarmy.azurecr.io/sso-service
  #name: castimaging/sso-service
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleServiceImage:
  name: registryarmy.azurecr.io/console
  #name: castimaging/console
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleGatewayServiceImage:
  name: registryarmy.azurecr.io/gateway
  #name: castimaging/gateway
  tag: army-latest-aku
  pullPolicy: IfNotPresent  
ConsoleAnalysisNodeImage:
  name: registryarmy.azurecr.io/analysis-node
  #name: castimaging/analysis-node
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleControlPaneImage:
  name: registryarmy.azurecr.io/admin-center
  #name: castimaging/admin-center
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleAuthenticationServiceImage:
  name: registryarmy.azurecr.io/auth-service
  #name: castimaging/auth-service
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ConsoleIntegratedDashboardsImage:
  name: registryarmy.azurecr.io/dashboards
  #name: castimaging/dashboards
  tag: army-2.12.5-SNAPSHOT-aku
  pullPolicy: IfNotPresent
  
#
# Viewer images
#
ViewerNeo4jImage:
  name: registryarmy.azurecr.io/neo4j
  #name: castimaging/neo4j
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ViewerServiceImage:
  name: registryarmy.azurecr.io/viewer
  #name: castimaging/viewer
  tag: army-latest-aku
  pullPolicy: IfNotPresent
ViewerEtlImage:
  name: registryarmy.azurecr.io/etl-service
  #name: castimaging/etl-service
  tag: army-latest-aku
  pullPolicy: IfNotPresent  
ViewerAiManagerImage:
  name: registryarmy.azurecr.io/ai-service
  #name: castimaging/ai-service
  tag: army-latest-aku
  pullPolicy: IfNotPresent
#
# ExtendProxy Image
#
ExtendProxyImage:
  name: registryarmy.azurecr.io/extend-proxy
  #name: castimaging/extend-proxy
  tag: army-latest-aku
  pullPolicy: IfNotPresent  
  
  
#
# Console resources
#
ConsolePostgresResources:
  requests:
    cpu: 1
    memory: 8G
SSOServiceResources:
  # limits:
    # cpu: 1
    # memory: 1G
  requests:
    cpu: 0.1
    memory: 100M
ConsoleServiceResources:
  # limits:
    # cpu: 1
    # memory: 1G
  requests:
    cpu: 0.1
    memory: 100M
GatewayServiceResources:
  # limits:
    # cpu: 1
    # memory: 1G
  requests:
    cpu: 0.1
    memory: 100M
AnalysisNodeReplicaResources:
  requests:
    cpu: 0.5
    memory: 4G
ControlPaneResources:
  # limits:
    # cpu: 1
    # memory: 1G
  requests:
    cpu: 0.1
    memory: 200M
AuthenticationServiceResources:
  # limits:
    # cpu: 1
    # memory: 1G
  requests:
    cpu: 0.1
    memory: 100M
IntegratedDashboardsResources:
  # limits:
    # cpu: 1
    # memory: 1G
  requests:
    cpu: 0.1
    memory: 100M

#
# Viewer resources
#
ViewerNeo4jResources:
  # limits:
    # cpu: 4
    # memory: 16G
  requests:
    cpu: 0.2
    memory: 12G
ViewerServerServiceResources:
  # limits:
    # cpu: 2500m
    # memory: 2528Mi
  requests:
    cpu: 0.1
    memory: 1G
ViewerEtlResources:
  # limits:
    # cpu: 2500m
    # memory: 3Gi
  requests:
    cpu: 0.1
    memory: 1G
ViewerAiManagerResources:
  # limits:
    # cpu: 2500m
    # memory: 3Gi
  requests:
    cpu: 0.1
    memory: 100M
    
#
# ExtendProxy resources
#
ExtendProxyResources:
  # limits:
    # cpu: 1
    # memory: 1G
  requests:
    cpu: 0.1
    memory: 100M    
    
storageClassName:
  name: castimaging-v3-local-storage
