apiVersion: v1
kind: Service
metadata:
  name: console-analysis-node
  labels:
    console.service: console-analysis-node
    component: core
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "8099"
      port: 8099
      targetPort: 8099
  selector:
    console.service: console-analysis-node  
    component: core
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    console.service: console-analysis-node
    version: {{ .Values.ConsoleAnalysisNodeImage.tag| default .Values.version }}
  name: console-analysis-node-core
  namespace: {{ .Release.Namespace }}   
spec:
  replicas: {{ .Values.AnalysisNodeReplicaCount }}
  selector:
    matchLabels:
      console.service: console-analysis-node
  template:
    metadata:
      labels:
        console.network/aip-network: "true"
        console.service: console-analysis-node
        component: core
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: "Always"
      initContainers:
        - name: init-shared-directories
          image: busybox
          command:
            - "sh"
            - "-c"
            - "mkdir -p {{ .Values.anadir.common }} {{ .Values.anadir.delivery }} {{ .Values.anadir.deploy }} {{ .Values.anadir.extensions }}; sleep 120"
          volumeMounts:
            - mountPath: {{ .Values.anadir.castdirmount }}
              name: castdir
            - mountPath: {{ .Values.anadir.datadirmount }}
              name: shared-datadir
      containers:
        - env:
            - name: DEPLOY_VOLUME_MACHINE
              value: {{ .Values.anadir.deploy }}
            - name: DELIVERY_VOLUME_MACHINE
              value: {{ .Values.anadir.delivery }}
            - name: SHARED_VOLUME_MACHINE
              value: {{ .Values.anadir.common }}
            - name: LOGS_VOLUME_MACHINE
              value: {{ .Values.anadir.logs }}
            - name: ANDATA_VOLUME_MACHINE
              value: {{ .Values.anadir.lisa }}
            - name: CONSOLE_REGISTRY_URL
              value: http://console-control-panel.{{ .Release.Namespace }}.svc.cluster.local:8098
            - name: HOST_AUTH_SERVICE
              value: console-authentication-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: PORT_AUTH_SERVICE
              value: "8092"
          image: "{{ .Values.ConsoleAnalysisNodeImage.name }}:{{ .Values.ConsoleAnalysisNodeImage.tag}}"
          imagePullPolicy: "{{ .Values.ConsoleAnalysisNodeImage.pullPolicy }}"
          name: console-analysis-node
          ports:
            - containerPort: 8099
              protocol: TCP
          resources:
            {{- toYaml .Values.AnalysisNodeResources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.anadir.castdirmount }}
              name: castdir
            - mountPath: {{ .Values.anadir.datadirmount }}
              name: shared-datadir
      restartPolicy: Always 
      imagePullSecrets:
        - name: castbuild-sec  
      volumes:
        - name: shared-datadir
          persistentVolumeClaim:
            claimName: pvc-shared-datadir
  volumeClaimTemplates:
    - metadata:
        name: castdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "100Gi"
        storageClassName: "{{ .Values.DiskClassName }}"            
