apiVersion: v1
kind: Service
metadata:
  labels:
    console.service: console-authentication-service
  name: console-authentication-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "8092"
      port: 8092
      targetPort: 8092
  selector:
    console.service: console-authentication-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    console.service: console-authentication-service
    version: {{ .Values.ConsoleAuthenticationServiceImage.tag| default .Values.version }}
  namespace: {{ .Release.Namespace }}
  name: console-authentication-service
spec:
  replicas: {{ .Values.AuthenticationServiceReplicaCount }}
  selector:
    matchLabels:
      console.service: console-authentication-service
  strategy: {}
  template:
    metadata:
      labels:
        console.network/aip-network: "true"
        console.service: console-authentication-service
    spec:
      containers:
        - env:
            - name: HOST_AUTH_SERVICE
              value: console-authentication-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: PORT_AUTH_SERVICE
              value: "8092"
            - name: HOST_CONTROL_PANEL
              value: console-control-panel.{{ .Release.Namespace }}.svc.cluster.local
            - name: PORT_CONTROL_PANEL
              value: "8098"
            - name: HOST_KEYCLOAK
              value: console-sso-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: PORT_KEYCLOAK
              value: "8096"
            - name: DB_HOST
              value: console-postgres.{{ .Release.Namespace }}.svc.cluster.local
            - name: DB_PORT
              value: "2285"
            - name: KC_USER
              value: "admin"
            - name: KC_PASSWORD
              value: "admin"
            - name: HOST_GATEWAY
              value: console-gateway-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: PORT_GATEWAY
              value: "8090"
            - name: NGINX_HOST
              value: https://{{ .Values.CloudFrontDomain }}
          image: "{{ .Values.ConsoleAuthenticationServiceImage.name }}:{{ .Values.ConsoleAuthenticationServiceImage.tag }}"
          imagePullPolicy: "{{ .Values.ConsoleAuthenticationServiceImage.pullPolicy }}"
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8092/actuator/health
            failureThreshold: 15
            periodSeconds: 5
            timeoutSeconds: 2
          name: console-authentication-service
          ports:
            - containerPort: 8092
              protocol: TCP
          resources:
            {{- toYaml .Values.AuthenticationServiceResources | nindent 12 }}
      restartPolicy: Always
      imagePullSecrets:
        - name: castbuild-sec  