{{- if not .Values.NoIngress }}
# ********************************************************************
# Ingress prerequisite for Amazon EKS:
# ********************************************************************
#    Install the Nginx Ingress Controller on the cluster:
#     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#     helm repo update
#     helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace \
#        --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb"
# ********************************************************************
# Ingress prerequisite for Google GKE:
# ********************************************************************
#    Install the Nginx Ingress Controller on the cluster:
#     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#     helm repo update
#     helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace \
#        --set controller.service.type=LoadBalancer \
#        --set controller.service.externalTrafficPolicy=Local \
#        --set controller.ingressClassResource.name=nginx \
#        --set controller.ingressClassResource.controllerValue="k8s.io/ingress-nginx" \
#        --set controller.ingressClassResource.enabled=true \
#        --set controller.ingressClassByName=true
# ********************************************************************
# Ingress prerequisite for Azure AKS:
# ********************************************************************
#    Install the Nginx Ingress Controller on the cluster:
#     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#     helm repo update
#     helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace \
#        --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz
# ********************************************************************
# Next installation steps (all providers):
# ********************************************************************
# - Update values.yaml to set FrontEndHost (and optionally ExtendProxy.exthostname) and apply helm to create the Ingress(es)
# - Create DNS NAME record(s) pointing at the external IP of the Ingress(es)
# - Create SSL certificate(s) for the host name(s)
# - Create TLS Secret(s) 
#       > "tls-secret-cast"
#       > and optionally "tls-secret-cast-extend" (if you plan to use extend-proxy service)
#   Using the SSL certificate files, for instance:
#     kubectl create secret tls tls-secret-cast --cert=path/to/tls.crt --key=path/to/tls.key -n castimaging-v3
#     or
#     kubectl create secret tls tls-secret-cast --cert=fullchain.pem --key=privkey.pem -n castimaging-v3
#     (fullchain.pem <=> tls.crt ; privkey.pem <=> tls.key)
# - Optional: Update console-authenticationservice-configmap.yaml with the certificate (first part of fullchain.pem) 
#             and Set: UseCustomTrustStore: true in values .yaml
# - Upgrade helm chart
# ********************************************************************
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: castimaging-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.ContextUrl.enable }}
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-set-headers: "{{ .Release.Namespace }}/custom-headers"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ (urlParse .Values.FrontEndHost).host }}
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ (urlParse .Values.FrontEndHost).host }}
    secretName: tls-secret-cast
  rules:
  - host: {{ (urlParse .Values.FrontEndHost).host }}
    http:
      paths:
  {{- if .Values.ContextUrl.enable }}
      - path: {{ .Values.ContextUrl.appcontext }}(/|$)(.*)
        pathType: ImplementationSpecific
  {{- else }}
      - path: /
        pathType: Prefix
  {{- end }}
        backend:
          service:
            name: console-gateway-service
            port:
              number: 8090
---
  {{- if .Values.ExtendProxy.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: extendproxy-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "3072m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-set-headers: "{{ .Release.Namespace }}/custom-headers-extend"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.ExtendProxy.exthostname }}
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ExtendProxy.exthostname }}
    secretName: tls-secret-cast-extend
  rules:
  - host: {{ .Values.ExtendProxy.exthostname }}
    http:
      paths:
      - path: /extendproxy(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: extendproxy
            port:
              number: 8085
  {{- end }}
---
# ConfigMap for custom headers
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: {{ .Release.Namespace }}
data:
  X-Forwarded-For: {{ (urlParse .Values.FrontEndHost).host }} 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers-extend
  namespace: {{ .Release.Namespace }}
data:
  X-Forwarded-For: {{ .Values.ExtendProxy.exthostname }}
{{- end }}