kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.BSclassName }}
  annotations:
    helm.sh/resource-policy: keep
provisioner: {{ .Values.storage.BSdriver }}
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.FSclassName }}
  annotations:
    helm.sh/resource-policy: keep
provisioner: {{ .Values.storage.FSdriver }}
parameters:
  provisioningMode: efs-ap 
  directoryPerms: "0777"
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-datadir
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep  
  labels:
    console.service: console-analysis-node
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.FSclassName }}
  csi:
    driver: {{ .Values.storage.FSdriver }}
    volumeHandle: {{ .Values.storage.EFSsystemID }}::{{ .Values.storage.EFSaccessPointID }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: pvc-shared-datadir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-datadir
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep  
  labels:
    console.service: console-analysis-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .Values.storage.FSclassName }}
---
# For storage postgres data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi  # Default for Postgres, change according to deployment and applications in portfolio
  storageClassName: {{ .Values.storage.BSclassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-server-log
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep  
  labels:
    console.service: viewer-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.BSclassName }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-etl-logs
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    console.service: viewer-etl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.BSclassName }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagingviewer-v3-aimanager-logs
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    console.service: viewer-aimanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.BSclassName }}
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-extendproxy-data
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep 
  labels:
    console.service: extendproxy 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Specify the storage size required
  storageClassName: {{ .Values.storage.BSclassName }}
