kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.BSclassName }}
  annotations:
    helm.sh/resource-policy: keep
provisioner: {{ .Values.storage.BSdriver }}
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.FSclassName }}
  annotations:
    helm.sh/resource-policy: keep
provisioner: {{ .Values.storage.FSdriver }}
parameters:
  provisioningMode: efs-ap 
  directoryPerms: "0777"
volumeBindingMode: Immediate
reclaimPolicy: Retain
