kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: castimaging-ebs
  annotations:
    helm.sh/resource-policy: keep
provisioner: ebs.csi.aws.com # Amazon EBS CSI driver
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain