apiVersion: v1
kind: Service
metadata:
  name: viewer-neo4j
  labels:
    app: viewer-neo4j
    component: core
    
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: browser
    - port: 7687
      targetPort: 7687
      name: bolt
    - port: 6362
      targetPort: 6362
      name: backup
  selector:
    app: viewer-neo4j
    component: core
---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: viewer-neo4j-core
  namespace: {{.Release.Namespace}}
spec:
  serviceName: viewer-neo4j
  replicas: {{.Values.ViewerNeo4jReplicaCount}}
  selector:
    matchLabels:
      app: viewer-neo4j
  template:
    metadata:
      labels:
        app: viewer-neo4j
        component: core
    spec:
      securityContext:
        runAsUser: 7474
        runAsGroup: 7474
        fsGroup: 7474
        fsGroupChangePolicy: "Always"      
      initContainers:
        - name: init-shared-directories
          image: busybox
          command:
            - "sh"
            - "-c"
            - "mkdir -p /var/lib/neo4j/config/neo4j5_data"
          volumeMounts:
            - name: confdir
              mountPath: /var/lib/neo4j/config
      containers:
        - name: viewer-neo4j
          image: "{{.Values.ViewerNeo4jImage.name}}:{{.Values.ViewerNeo4jImage.tag}}"
          imagePullPolicy: "{{.Values.ViewerNeo4jImage.pullPolicy}}"
          command: ['sh', '-c', "chmod u+x /var/lib/neo4j/config/data-model/*sh; /var/lib/neo4j/config/init.sh"]
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_dbms_memory_heap_maxSize
              value: "12G"
            - name: TIME_ZONE
              value: "Europe/Paris"
          ports:
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
            - containerPort: 6362
              name: backup

          resources:
            {{- toYaml .Values.ViewerNeo4jResources | nindent 12 }}
          volumeMounts:
            - name: logdir
              mountPath: /logs
            - name: confdir
              mountPath: /var/lib/neo4j/config
            - name: neo4jconf
              mountPath: /var/lib/neo4j/config/configuration/neo4j.conf
              subPath: neo4j.conf
            - name: initsh
              mountPath: /var/lib/neo4j/config/init.sh
              subPath: init.sh
            - name: apocconf
              mountPath: /var/lib/neo4j/config/configuration/apoc.conf
              subPath: apoc.conf
      volumes:
        - name: neo4jconf
          configMap:
            name: neo4jconf
            defaultMode: 0777
        - name: initsh
          configMap:
            name: neo4jinitsh
            defaultMode: 0777
        - name: apocconf
          configMap:
            name: neo4japocconf
            defaultMode: 0777

  volumeClaimTemplates:
    - metadata:
        name: logdir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ .Values.storage.className }}"
        resources:
          requests:
            storage: "1Gi"
    - metadata:
        name: confdir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ .Values.storage.className }}"
        resources:
          requests:
            storage: "6Gi"