kind: Service
apiVersion: v1
metadata:
  name: viewer-aimanager
  labels:
    app: viewer-aimanager
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: viewer-aimanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: viewer-aimanager
    version: {{.Values.ViewerAiManagerImage.tag| default .Values.version}}
  name: viewer-aimanager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ViewerAiManagerReplicaCount }}
  selector:
    matchLabels:
      app: viewer-aimanager
  template:
    metadata:
      labels:
        app: viewer-aimanager
    spec:
      containers:
        - image: "{{ .Values.ViewerAiManagerImage.name }}:{{ .Values.ViewerAiManagerImage.tag}}"
          imagePullPolicy: "{{ .Values.ViewerAiManagerImage.pullPolicy }}"
          command: ['sh', '-c', "ls -l /opt/imaging/open_ai-manager/config/ && /opt/imaging/open_ai-manager/config/init.sh"]
          #command: ['sh', '-c', "sleep 3000 && ls -l /opt/imaging/open_ai-manager/config/ && /opt/imaging/open_ai-manager/config/init.sh"]
          name: viewer-aimanager
          #securityContext:
            #runAsUser: 0
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            {{- toYaml .Values.ViewerAiManagerResources | nindent 12 }}
          volumeMounts:
            - name: aimanagerconfig
              mountPath: /opt/imaging/open_ai-manager/config
              readOnly: false
            - name: csv
              mountPath: /opt/imaging/open_ai-manager/csv
              readOnly: false
            - name: logdir
              mountPath: /opt/imaging/open_ai-manager/logs
              readOnly: false
            - name: openaiappconfig
              mountPath: /opt/imaging/open_ai-manager/config/app.config
              subPath: app.config
      volumes:
        - name: aimanagerconfig
          configMap:
          persistentVolumeClaim:
            claimName: pvc-imagingviewer-v3-aimanager-config
        - name: csv
          persistentVolumeClaim:
            claimName: pvc-imagingviewer-v3-aimanager-csv
        - name: logdir
          persistentVolumeClaim:
            claimName: pvc-imagingviewer-v3-aimanager-logs
        - name: openaiappconfig
          configMap:
            name: openaiappconfig