apiVersion: v1
data:
  app.config: |-
    GPT_KEY=""
    DB_HOST="console-postgres.{{ .Release.Namespace }}.svc.cluster.local"
    DB_PORT=2285
    DB_PASSWORD="CastAIP"
    DB_USER="operator"
    DB_SCHEMA="postgres"
    NEO4J_URI="bolt://{{ .Values.Neo4jHostName }}:7687"
    NEO4J_USER="neo4j"
    NEO4J_PASSWORD="imaging"
    DEBUG=False
    PORT=8082
    LOGS_FOLDER='/opt/imaging/open_ai-manager/logs'
    CSV_FOLDER='/opt/imaging/open_ai-manager/csvs'
    EXECUTABLE_PATH='/opt/imaging/open_ai-manager/nlp_modules/moduleBuilderLean'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: openaiappconfig
  namespace: {{.Release.Namespace}}
